#  \
#  \\,
#   \\\,^,.,,.                     Zero to Hero
#   ,;7~((\))`;;,,               <zerotohero.dev>
#   ,(@') ;)`))\;;',    stay up to date, be curious: learn
#    )  . ),((  ))\;,
#   /;`,,/7),)) )) )\,,
#  (& )`   (,((,((;( ))\,

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: fizz
  name: idm
data:
  FIZZ_IDM_SVC_PORT: "9002"
  FIZZ_IDM_USERS_TABLE_NAME: "users"
  FIZZ_IDM_DB_NAME: "fizz"
  FIZZ_IDM_VERIFIED_URL: "http://localhost/verified"
  FIZZ_IDM_CRYPTO_ENDPOINT_URL: "http://localhost:9001/"
  FIZZ_IDM_MAILER_ENDPOINT_URL: "http://localhost:9005/"
