#  \
#  \\,
#   \\\,^,.,,.                     Zero to Hero
#   ,;7~((\))`;;,,               <zerotohero.dev>
#   ,(@') ;)`))\;;',    stay up to date, be curious: learn
#    )  . ),((  ))\;,
#   /;`,,/7),)) )) )\,,
#  (& )`   (,((,((;( ))\,

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fizz
  name: idm
  labels:
    app: idm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idm
  template:
    metadata:
      labels:
        app: idm
    spec:
      containers:
      - name: idm
        image: 340111760086.dkr.ecr.us-west-2.amazonaws.com/fizz-idm:0.0.16
        ports:
        - containerPort: 9002
        env:
          - name: FIZZ_DEPLOYMENT_TYPE
            valueFrom:
              configMapKeyRef:
                name: common
                key: FIZZ_DEPLOYMENT_TYPE
          - name: FIZZ_LOG_DESTINATION
            valueFrom:
              secretKeyRef:
                name: common
                key: FIZZ_LOG_DESTINATION
          - name: FIZZ_IDM_SVC_PORT
            valueFrom:
              configMapKeyRef:
                name: idm
                key: FIZZ_IDM_SVC_PORT
          - name: FIZZ_IDM_HONEYBADGER_API_KEY
            valueFrom:
              secretKeyRef:
                name: idm
                key: FIZZ_IDM_HONEYBADGER_API_KEY
          - name: FIZZ_IDM_USERS_TABLE_NAME
            valueFrom:
              configMapKeyRef:
                name: idm
                key: FIZZ_IDM_USERS_TABLE_NAME
          - name: FIZZ_IDM_VERIFIED_URL
            valueFrom:
              configMapKeyRef:
                name: idm
                key: FIZZ_IDM_VERIFIED_URL
          - name: FIZZ_IDM_CRYPTO_ENDPOINT_URL
            valueFrom:
              configMapKeyRef:
                name: idm
                key: FIZZ_IDM_CRYPTO_ENDPOINT_URL
          - name: FIZZ_IDM_MAILER_ENDPOINT_URL
            valueFrom:
              configMapKeyRef:
                name: idm
                key: FIZZ_IDM_MAILER_ENDPOINT_URL
          - name: FIZZ_IDM_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: idm
                key: FIZZ_IDM_DB_NAME
          - name: FIZZ_IDM_DB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: idm
                key: FIZZ_IDM_DB_CONNECTION_STRING
          - name: FIZZ_IDM_PATH_PREFIX
            valueFrom:
              configMapKeyRef:
                name: idm
                key: FIZZ_IDM_PATH_PREFIX
          - name: FIZZ_IDM_PATH_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: idm
                  key: FIZZ_IDM_LAUNCH_STATE
