#  \
#  \\,
#   \\\,^,.,,.                    “Zero to Hero”
#   ,;7~((\))`;;,,               <zerotohero.dev>
#   ,(@') ;)`))\;;',    stay up to date, be curious: learn
#    )  . ),((  ))\;,
#   /;`,,/7),)) )) )\,,
#  (& )`   (,((,((;( ))\,

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fizz
  name: store
  labels:
    app: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store
        image: zerotohero-dev/fizz-store:0.0.10
        ports:
        - containerPort: 9004
        env:
          - name: FIZZ_DEPLOYMENT_TYPE
            valueFrom:
              configMapKeyRef:
                name: common
                key: FIZZ_DEPLOYMENT_TYPE
          - name: FIZZ_LOG_DESTINATION
            valueFrom:
              secretKeyRef:
                name: common
                key: FIZZ_LOG_DESTINATION
          - name: FIZZ_STORE_SVC_PORT
            valueFrom:
              configMapKeyRef:
                name: store
                key: FIZZ_STORE_SVC_PORT
          - name: FIZZ_STORE_HONEYBADGER_API_KEY
            valueFrom:
              secretKeyRef:
                name: store
                key: FIZZ_STORE_HONEYBADGER_API_KEY
          - name: FIZZ_STORE_CRYPTO_ENDPOINT_URL
            valueFrom:
              configMapKeyRef:
                name: store
                key: FIZZ_STORE_CRYPTO_ENDPOINT_URL
          - name: FIZZ_STORE_IDM_ENDPOINT_URL
            valueFrom:
              configMapKeyRef:
                name: store
                key: FIZZ_STORE_IDM_ENDPOINT_URL
          - name: FIZZ_STORE_USERS_TABLE_NAME
            valueFrom:
              configMapKeyRef:
                name: store
                key: FIZZ_STORE_USERS_TABLE_NAME
          - name: FIZZ_STORE_PLANS_TABLE_NAME
            valueFrom:
              configMapKeyRef:
                name: store
                key: FIZZ_STORE_PLANS_TABLE_NAME
          - name: FIZZ_STORE_STRIPE_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: store
                key: FIZZ_STORE_STRIPE_PRIVATE_KEY
          - name: FIZZ_STORE_STRIPE_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: store
                key: FIZZ_STORE_STRIPE_PUBLIC_KEY
          - name: FIZZ_STORE_SUBSCRIBE_API_URL
            valueFrom:
              configMapKeyRef:
                name: store
                key: FIZZ_STORE_SUBSCRIBE_API_URL
          - name: FIZZ_STORE_SUBSCRIBE_SUCCESS_URL
            valueFrom:
              configMapKeyRef:
                name: store
                key: FIZZ_STORE_SUBSCRIBE_SUCCESS_URL
          - name: FIZZ_STORE_SUBSCRIBE_ERROR_URL
            valueFrom:
              configMapKeyRef:
                name: store
                key: FIZZ_STORE_SUBSCRIBE_ERROR_URL

