#  \
#  \\,
#   \\\,^,.,,.                     Zero to Hero
#   ,;7~((\))`;;,,               <zerotohero.dev>
#   ,(@') ;)`))\;;',    stay up to date, be curious: learn
#    )  . ),((  ))\;,
#   /;`,,/7),)) )) )\,,
#  (& )`   (,((,((;( ))\,

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fizz
  name: mailer
  labels:
    app: mailer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
      - name: mailer
        image: 340111760086.dkr.ecr.us-west-2.amazonaws.com/fizz-mailer:0.0.14
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: 9001
        env:
          - name: FIZZ_DEPLOYMENT_TYPE
            valueFrom:
              configMapKeyRef:
                name: common
                key: FIZZ_DEPLOYMENT_TYPE
          - name: FIZZ_LOG_DESTINATION
            valueFrom:
              secretKeyRef:
                name: common
                key: FIZZ_LOG_DESTINATION
          - name: FIZZ_MAILER_SVC_PORT
            valueFrom:
              configMapKeyRef:
                name: mailer
                key: FIZZ_MAILER_SVC_PORT
          - name: FIZZ_MAILER_EMAIL_VERIFICATION_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: mailer
                key: FIZZ_MAILER_EMAIL_VERIFICATION_BASE_URL
          - name: FIZZ_MAILER_WEB_APP_HOST_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: mailer
                key: FIZZ_MAILER_WEB_APP_HOST_BASE_URL
          - name: FIZZ_MAILER_PASSWORD_RESET_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: mailer
                key: FIZZ_MAILER_PASSWORD_RESET_BASE_URL

          - name: FIZZ_MAILER_MAILGUN_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: mailer
                key: FIZZ_MAILER_MAILGUN_DOMAIN
          - name: FIZZ_MAILER_HONEYBADGER_API_KEY
            valueFrom:
              secretKeyRef:
                name: mailer
                key: FIZZ_MAILER_HONEYBADGER_API_KEY
          - name: FIZZ_MAILER_MAILGUN_API_KEY
            valueFrom:
              secretKeyRef:
                name: mailer
                key: FIZZ_MAILER_MAILGUN_API_KEY
          - name: FIZZ_MAILER_PATH_PREFIX
            valueFrom:
              configMapKeyRef:
                name: mailer
                key: FIZZ_MAILER_PATH_PREFIX

