#  \
#  \\,
#   \\\,^,.,,.                     Zero to Hero
#   ,;7~((\))`;;,,               <zerotohero.dev>
#   ,(@') ;)`))\;;',    stay up to date, be curious: learn
#    )  . ),((  ))\;,
#   /;`,,/7),)) )) )\,,
#  (& )`   (,((,((;( ))\,

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: fizz
  name: mailer
data:
  FIZZ_MAILER_SVC_PORT: "9005"
  FIZZ_MAILER_EMAIL_VERIFICATION_BASE_URL: "http://localhost/verification/base"
  FIZZ_MAILER_WEB_APP_HOST_BASE_URL: "http://localhost/web/host/base"
  FIZZ_MAILER_PASSWORD_RESET_BASE_URL: "http://localhost/password/reset/base"
  FIZZ_MAILER_MAILGUN_DOMAIN: "hermes.fizzbuzz.pro"
  FIZZ_MAILER_PATH_PREFIX: "/mailer"
