#  \
#  \\,
#   \\\,^,.,,.                     Zero to Hero
#   ,;7~((\))`;;,,               <zerotohero.dev>
#   ,(@') ;)`))\;;',    stay up to date, be curious: learn
#    )  . ),((  ))\;,
#   /;`,,/7),)) )) )\,,
#  (& )`   (,((,((;( ))\,

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fizz
  name: crypto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto
  template:
    metadata:
      labels:
        app: crypto
    spec:
      containers:
      - name: crypto
        image: 340111760086.dkr.ecr.us-west-2.amazonaws.com/fizz-crypto:0.0.10
        ports:
        - containerPort: 9001
        env:
          - name: FIZZ_DEPLOYMENT_TYPE
            valueFrom:
              configMapKeyRef:
                name: common
                key: FIZZ_DEPLOYMENT_TYPE
          - name: FIZZ_LOG_DESTINATION
            valueFrom:
              secretKeyRef:
                name: common
                key: FIZZ_LOG_DESTINATION
          - name: FIZZ_CRYPTO_SVC_PORT
            valueFrom:
              configMapKeyRef:
                name: crypto
                key: FIZZ_CRYPTO_SVC_PORT
          - name: FIZZ_CRYPTO_JWT_KEY
            valueFrom:
              secretKeyRef:
                name: crypto
                key: FIZZ_CRYPTO_JWT_KEY
          - name: FIZZ_CRYPTO_RANDOM_BYTE_LENGTH
            valueFrom:
              configMapKeyRef:
                name: crypto
                key: FIZZ_CRYPTO_RANDOM_BYTE_LENGTH
          - name: FIZZ_CRYPTO_BCRYPT_HASH_ROUNDS
            valueFrom:
              configMapKeyRef:
                name: crypto
                key: FIZZ_CRYPTO_BCRYPT_HASH_ROUNDS
          - name: FIZZ_CRYPTO_AES_PASSPHRASE
            valueFrom:
              secretKeyRef:
                name: crypto
                key: FIZZ_CRYPTO_AES_PASSPHRASE
          - name: FIZZ_CRYPTO_HONEYBADGER_API_KEY
            valueFrom:
              secretKeyRef:
                name: crypto
                key: FIZZ_CRYPTO_HONEYBADGER_API_KEY
          - name: FIZZ_CRYPTO_JWT_EXPIRY_HOURS
            valueFrom:
              configMapKeyRef:
                name: crypto
                key: FIZZ_CRYPTO_JWT_EXPIRY_HOURS
